# Generated by Django 5.0 on 2026-09-27 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('skills', models.TextField(blank=True, help_text='Separate skills with commas')),
                ('education', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('links', models.TextField(blank=True, help_text='Add links, one per line')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
