# Generated by Django 6.1.1 on 2026-09-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_location_profile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_location_to_recruiters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_projects_to_recruiters',
            field=models.BooleanField(default=True),
        ),
    ]
