# Generated by Django 5.0 on 2026-09-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('company', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('skills', models.TextField(blank=True, help_text='Separate skills with commas')),
                ('description', models.TextField(blank=True)),
                ('salary', models.PositiveIntegerField(blank=True, help_text='Yearly salary', null=True)),
                ('remote', models.BooleanField(default=False)),
                ('visa_sponsorship', models.BooleanField(default=False)),
            ],
        ),
    ]
