# Generated by Django 5.2.17 on 2026-09-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="seen_profile_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
