# Generated by Django 5.2.17 on 2026-09-25 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_merge_duplicate_skills"),
        ("jobs", "0002_savedsearch_seen_profile_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="DismissedRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissed_recommendations",
                        to="jobs.job",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissed_recommendations",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "profile")},
            },
        ),
    ]
