# Generated by Django 5.2.17 on 2026-09-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_notification_savedsearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                choices=[("intern", "Internship"), ("full_time", "Full-time")],
                default="full_time",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Hourly wage for internships, yearly salary for full-time roles",
                null=True,
            ),
        ),
    ]
