# Generated by Django 5.2.17 on 2026-09-25 06:28

from django.db import migrations


def merge_duplicate_skills(apps, schema_editor):
    Skill = apps.get_model('accounts', 'Skill')
    keep_by_name = {}
    for skill in Skill.objects.order_by('pk'):
        key = skill.name.lower()
        keep = keep_by_name.setdefault(key, skill)
        if keep.pk == skill.pk:
            continue
        for profile in skill.profiles.all():
            profile.skills.add(keep)
        for project in skill.projects.all():
            project.skills.add(keep)
        for job in skill.jobs.all():
            job.skills.add(keep)
        skill.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_skills, migrations.RunPython.noop),
    ]
